# Generated by Django 4.1.7 on 2023-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact_orders_alter_product_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=900)),
                ('address', models.CharField(max_length=112)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=112)),
                ('zip_code', models.CharField(max_length=112)),
                ('phone', models.CharField(max_length=112)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
