# Generated by Django 4.1.7 on 2023-04-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
